broker:
  debug:
    flask_debug: on # on or false

  host:
    ip: ip address
    port: port number

  # a secret key for Flask application.
  secret_key: some secret key

  kafka:
    host: kafka host
    port: kafka port
    topic: kafka topic
    group: kafka group