broker:
  debug:
    flask_debug: on # on or false

  host:
    ip: ip address
    port: port number

  # a secret key for Flask application.
  secret_key: some secret key

  scheduler:
    type: rabbitmq
    server:
      host: rabbitmq host
      port: rabbitmq port
    exchange: ploto
    queue: gidat_plot_task_queue
    routing_keys:
      pattern: plot.task.*
      default: plot.task.default